### ISSUE TITLE
new yaml based on home-assistant-voice-pe 26.4.0

### ISSUE THREAD

**Issue by future159** [KristopherMackowiak/ha_voice_assistant#18]
here is the new version of the yaml, based on the home-assistant-voice-pe 26.4.0
with sendspin support and esphome 2026.3.0

[home-assistant-voice.yaml](https://github.com/user-attachments/files/27310578/home-assistant-voice.yaml)

**Comment by Another-Taipan** [comment]
Tried to compile with ESPHome ver 2026.5.3, but got fatal error:

`In file included from src/esphome/components/sendspin/media_source/sendspin_decoder.cpp:1:
src/esphome/components/sendspin/media_source/sendspin_decoder.h:11:10: fatal error: flac_decoder.h: No such file or directory`

I would appreciate some guidance on what I need to do to fix this error, please?

**Comment by Another-Taipan** [comment]
@future159 - I am sorry to be a pest, but I think that I really need your help to resolve this compilation issue.  I can provide more detailed information, if you require?

I have tried cleaning the build files, resetting the build environment and a whole lot of suggestions from Google's Gemini.  But I have not had any success so far.  And I have tried the latest ESPHome version - ver 2026.6.2.

**Comment by Another-Taipan** [comment]
With the assistance of @OzGav I now have a version of the YAML that will happily compile with ESPHome ver. 2026.6.2.

The main change was that Sendspin, media_source and http_request are now built into ESPHome (2026.6.0+), so they no longer need to be pinned. Only voice_kit is still an external component.  The corrected version is attached ...

[corrected.yaml](https://github.com/user-attachments/files/29406629/corrected.yaml)
